version: '3.4'
services:

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8001:80    

  postgres:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
